[package]
name = "laggit_backend"
version = "0.2.2"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
diesel = { version = "1.4.1", features = ["postgres", "chrono", "r2d2"] }
diesel_migrations = "1.4.0"
r2d2 = "0.8.3"
juniper = "0.11.1"
juniper_codegen = "0.11.1"
juniper_rocket = "0.2.0"
dotenv = "0.13.0"
serde = "1.0.88"
serde_json = "1.0.38"
serde_derive = "1.0.88"
chrono = { version = "0.4.6", features = ["serde"] }
orion = "0.13.1"
hex = "0.3.2"
frank_jwt = "3.1.0"

